### ISSUE TITLE
Test Group E MiniTwit

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#101]
Go through their application

In case you find non-functional/erroneous behavior please report it via issues to the respective Github repositories (find them in [repositories.py](https://github.com/itu-devops/lecture_notes/blob/479a5fd72b575d8d4f81cc8d33e93b6decc967c9/repositories.py#L30-L36)).

**Comment by Turboen** [comment]
- [ ] Do you see a public timeline?
- [ ] Does the public timeline show messages that the application received from the simulator?
- [ ] Can you create a new user?
- [ ] Can you login as a new user?
- [ ] Can you write a message?
- [ ] After publishing a message, does it appear on you private timeline?
- [ ] Can you follow another user?

**Comment by Lucki2g** [comment]
![image](https://user-images.githubusercontent.com/11597762/157460239-411faa19-2639-4d52-951e-d23a77bb2cf8.png)

**Comment by Thomsen96** [comment]
This should be moved to a new issue on their issue board.

**Comment by ValarMarkhulis** [comment]
@Lucki2g, please create an issue on group E's repo and close this issue.

**Comment by Lucki2g** [comment]
Created on their repo [issue 35](https://github.com/ChadIImus/Devoops/issues/35)
