### ISSUE TITLE
Setup minitoring

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#103]
We could add:
information from database:
- [x] Amount of users
- [x] Amount of tweets
- [x] Registered users
- [x] Messages
- [x] Followers
- [x] Top 10 users that follows other users
- [x] Top 10 users that is the most followed
- [x] who tweets the most
- [x] how many tweet are there pr users (think bel curve) maybe?

Information from minitwit:
- [x] Latest
- [x] distribution of http status codes
- [x] average response time on the endpoints
- [x] if we have an http error code. what endpoint is it
- [x] How many request have we served
- [x] Total_http_requests
- [x] Total_http_errors
- [x] Fastest/slowest endpoints
- [ ] ...

**Comment by Turboen** [comment]
Developed in branch - [](https://github.com/DevelOpsITU/MiniTwit/tree/feature/%23103-setup-monitoring)

**Comment by Turboen** [comment]
A prometheus image is created in the docker-compose.yaml file
- The image is hosted at port 9090 (this is used for grafana (http://prometheus:9090)


**/metric**
- This endpoint is added to minitwit-app
- Shows the prometheus metric data

**Comment by Turboen** [comment]
**Metrics from minitwit to include in prometheus:**
- [ ] Latest
- [ ] Total_http_requests
- [ ] Total_http_errors

**Comment by Lucki2g** [comment]
**Information from postgres server:**
What is interesting to know business wise?
- [ ] Amount of users
- [ ] Amount of tweets
- [ ] Last tweet?

**Comment by Thomsen96** [comment]
This issues should maybe also include and in the end close #104.

With the last commit that i posted was there added information that shows some quick information/ stats of the minitwit database.

![billede](https://user-images.githubusercontent.com/32035863/158031372-10445f47-5a73-479e-b641-7bb4ea809163.png)

**Comment by Thomsen96** [comment]
![billede](https://user-images.githubusercontent.com/32035863/158032115-ecd31738-13c3-4209-a8dd-0c95241b40ae.png)

**Comment by Thomsen96** [comment]
Woop woop I got the node exporter to work! 🥇 

Used this example: https://grafana.com/grafana/dashboards/12486

So now do we have the cpu, memory network stats from all our VMs b325f14e18e915d567f17b41350b8364772a527e

![billede](https://user-images.githubusercontent.com/32035863/158260002-532e59f2-a9d3-4203-985c-ad0a01646714.png)

**Comment by Turboen** [comment]
![image](https://user-images.githubusercontent.com/61050781/158388554-89516b05-4331-4896-bac6-2f48a838fd2f.png)

![image](https://user-images.githubusercontent.com/61050781/158391014-e50db1ae-2ccf-46ed-b495-ea1b60cecee3.png)
