### ISSUE TITLE
Setup Visualization

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#104]

**Comment by Turboen** [comment]
Developed in branch - [Feature/#103-Setup-Monitoring](https://github.com/DevelOpsITU/MiniTwit/tree/feature/%23103-setup-monitoring)

**Comment by Turboen** [comment]
A grafana image is created in the docker-compose.yaml file
- The server is hosted at port **3000**

**Comment by Thomsen96** [comment]
I think that it is smart that we have a local development Grafana and Prometheus. so that we can test and work with them locally. Just like we must have a local Postgres database at some point. But the username/password for local development is okay being admin/admin. It is not exposed to the www.
