### ISSUE TITLE
Features of MiniTwit template

### ISSUE THREAD

**Issue by ValarMarkhulis** [DevelOpsITU/MiniTwit#11]
This issue will list the features of MiniTwit that needs to be converted from python to the new application language.

Status for each web framework will be kept in issues #5 and #6 

**Web Framework and templating**

Serving includes mapping of Jinja and Flask specific function calls like flash(), gavatar() and get_flashed_messages()

Mark sub tasks completed with: ✔️
- [ ] Serve "/" 
- ❌ Redirect to /public if no cookie or username in cookie is empty
- ❌ Serve My timeline
- [ ] Serve "/public"
- ❌ Show top 30 latest messages that aren't flagged
- [ ] Serve "/login" 
- ❌ Read urlencodedform data
- ❌ Check user against password hash in database
- ❌ Redirect user to "/" if successful login
- ❌ Redirect user to /login if login did not match
- ❌ Show flash message of what went wrong
- [ ] Serve "/logout" 
- ❌ Overwrite cookie UserId
- ❌ Send message of logout
- ❌ Redirect to /public
- [ ] Serve "/register" 
- ❌ Serve the GET request
- ❌ Create user in database
- ❌ Error handling
- ❌ Redirection to /login on success
- [ ] Serve "/username"
- ❌ Show the users Twits
- [ ] Serve "/username/follow"
- ❌ Add the current user as a follower of the given user
- ❌ Error handling
- [ ] Serve "/username/unfollow"
- ❌ Remove the current user as a follower of the given user
- ❌ Error handling
- [ ] Serve "/add_message"
- ❌ Register a new message for the user
- ❌ Error handling
- [ ] Serve "static/style.css"
- [ ] Get cookies
- [ ] Set cookies
- [ ] Access urlencodedforms and their data
- [ ] make flash() alternative #9 

**Database**

- [ ] Database connection
- [ ] GetPublicTimelie
- [ ] GetUsersTimeLine
- [ ] GetPrivateTimeline
- [ ] GetUserId
- [ ] GetUser
- [ ] SaveUser
- [ ] SaveMessage

**Misc**

- [ ] Verification of passwords
- [ ] Generation of password
- [ ] Generate Gavatar links
- [ ] Cookie management handeling
- [ ] Format epoch time to correct timestamp format

**Comment by DannyDelic** [comment]
MiniTwit has been moved to go, so ticket is closed.
