### ISSUE TITLE
Error found in follower table from the database migration and misleading error message

### ISSUE THREAD

**Issue by ValarMarkhulis** [DevelOpsITU/MiniTwit#112]
1 day after the release of [1.3.0](https://github.com/DevelOpsITU/MiniTwit/releases/tag/v1.3.0), we noticed that there was a lot of warnings and errors being reported on the server, when running the command ` docker-compose logs -f --tail 100 ` on the server from the ApplicationServer folder:  
![image](https://user-images.githubusercontent.com/11947367/158057660-5d831fb3-0de4-432f-920f-29993c29ba1f.png)

We then started investigating how the database looked, and why the errors are thrown.
First @Thomsen96 and I, saw that the follower table in the column "whom_id" was all 0, besides the 4 testing "follows" I tried out.
![image](https://user-images.githubusercontent.com/11947367/158057796-c39840f1-3a4a-43ed-bb44-20d9219a9da9.png)

So something must have gone wrong with the migration in #89.

Secondly, we noticed that the error message from follow scenario that failed, did not make sense. We checked that the user was there, but the person they wanted to follow did not exist in the database. So there is a copy-paste error in the error message in line 66

https://github.com/DevelOpsITU/MiniTwit/blob/dbebd4a1738072be8400defee054fd51857c5af4/logic/user.go#L54-L68

It should be like this

```log...Str("username", usernameToFollow).Msg("Could not get user")```

So the error was correctly thrown since the simulator tried to have an existing user follow a user we did not have in our database. But the error message is wrong.

**Comment by Lucki2g** [comment]
After running the simulator locally I observe that no followers entries are created
![image](https://user-images.githubusercontent.com/11597762/158376047-59e8bc5e-4c26-45c5-8352-c77145e88dd7.png)
Neither are any tweets! Everything is returning 400
![image](https://user-images.githubusercontent.com/11597762/158376143-cbc90cab-090f-45d2-b0ee-757da5432192.png)

**Comment by Lucki2g** [comment]
Trying to do everything through Postman
1. Register user 1
![image](https://user-images.githubusercontent.com/11597762/158389985-d5b9e8ce-be3a-4165-8a9c-02d7a10388cb.png)
User can login in afterwards [👍](https://emojipedia.org/thumbs-up/)
2. Register user 2
![image](https://user-images.githubusercontent.com/11597762/158390151-b15fa8c7-e2a0-44bc-be93-eef30e78b87c.png)
User can login afterwards [👍](https://emojipedia.org/thumbs-up/)
3. Have user 1 follow user 2 & the other way around
![image](https://user-images.githubusercontent.com/11597762/158391338-ade2ec1c-f59f-41bd-be22-a8f35f1ee706.png)![image](https://user-images.githubusercontent.com/11597762/158392441-ddf48b21-ba8c-4e3c-994a-a10d4e590ef8.png)
Visible in db

**Comment by Lucki2g** [comment]
## SOLUTION
We have concluded from previous observations and the fact that we ran the simulator on our production (which worked), that we are just missing all the users that Helge's simulator uses.
Therefore, we have decided to introduce a **"dirty hack"** at the follow endpoint, to register any user not found in the database

**Comment by Thomsen96** [comment]
This issue have been "solved" / mitigated in #119 and i have created a new issues that should add monitoring to the mitigation. Therefor I will close this issue.
