### ISSUE TITLE
Add code linting, code analysis, vulnerability checks

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#113]
- [x] [Go lint](https://github.com/golang/lint)
- `go get -u golang.org/x/lint/golint`
- stand in root and run `golint -set_exit_status ./...` to run everything
- current result from dev: `Found 111 lint suggestions; failing.` and a large trace e.g. `models\models.go:35:6: exported type Twit should have comment or be unexported`

- [x] shell checker
- [x] synk (docker scan) **((Uses azure/container-scan instead))**
- [x] ScanCode

- [ ] #134

**Comment by ValarMarkhulis** [comment]
This is sort of a duplicate of issues #117 and #69.
Go linting is being done from the script: [golinter.sh](https://github.com/DevelOpsITU/MiniTwit/blob/7d425f8a7e31dde29071c83f76787460fe3c80b1/scripts/golinter.sh), which can be found on the ` feature/#117_Setup_Github_action_as_CI` branch.

**Comment by ValarMarkhulis** [comment]
See this [github workflow](https://github.com/DevelOpsITU/MiniTwit/runs/5634305253?check_suite_focus=true) under Scancode, for the output for the scancode command run in this [docker image ](https://github.com/DevelOpsITU/MiniTwit/blob/feature/%23117_Setup_Github_action_as_CI/scripts/scancode/Dockerfile).
