### ISSUE TITLE
Add Maintainability and Technical Debt estimation tools

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#114]
Add all of the following three tools to your projects:

[Sonarqube](https://sonarcloud.io/)
After doing the exercises you should already have done this.
[Code Climate](https://codeclimate.com/)
[Better Code Hub](https://bettercodehub.com/)

The task should be easy and quick to perform. To any of the three tools, you can login via Github and just select the corresponding repository/-ies.

In case Better Code Hub complains that your system is too big to be analyzed, you can upgrade your plan with the Github education pack.

React on the issues that these tools are 'complaining' about. You do not have to fix everything. But prominent issues that you agree on, should be fixed from now on. Be aware of that the tools automatically analyze new versions of your projects, i.e., check that your future work does not introduce new issues and decreases the quality metrics.

**Comment by Lucki2g** [comment]
currently setting up sonarcloud on branch #feature/#114

**Comment by ValarMarkhulis** [comment]
Could also add this [project](https://github.com/gojp/goreportcard). I got it running locally:
![image](https://user-images.githubusercontent.com/11947367/158688728-aa620ec6-9d1b-4254-b1da-080ba1f3b741.png)

**Comment by Lucki2g** [comment]
Currently have current problem with sonarcloud:
![image](https://user-images.githubusercontent.com/11597762/159119404-21d025a8-16bc-4888-b04c-0f95cb4a78d8.png)
To disable I must go to sonarcloud website and disable it in `Administration > Analysis Method`. However I do not see this option. It may be a permissions problem on sonarcloud.

**Comment by Lucki2g** [comment]
Request has been sent to "owner of repo" for both Code Climate & Better Code Hub
![image](https://user-images.githubusercontent.com/11597762/159119682-a8d35ff8-5a95-4ea6-ae9f-4574c6c7cbc1.png)

**Comment by Thomsen96** [comment]
All third party access requests have been granted.
![billede](https://user-images.githubusercontent.com/32035863/159120905-27f26497-ed40-4654-8f30-1638f117fb1b.png)

**Comment by Lucki2g** [comment]
# Summary
### Better Code Hub
Does not have much configuration for when to run, besides a single button for automatic pull request run. (which I enabled)
You can do some configuration in the .bettercodehub.yml in the root directory:

- Exclude files and directories from analysis
- Configure programming languages
- Define architecture components
- Customize file filtering

This is how it went for the main branch. A batch has also been added to the readme.md on dev to flex quality.
To see the weighted metric go to [link](https://bettercodehub.com/results/DevelOpsITU/MiniTwit)
![image](https://user-images.githubusercontent.com/11597762/159122063-96bbb34d-4a8f-4dce-9541-ab7ea2f91da9.png)
#### Highlights
The major issues better code hub finds are:
- too long files (not allowed to be > 60 lines)
- code duplication (according to it we have 0 lines of non duplicated code)
- no interfaces
- missing automated tests

### Code Climate
Has github actions for test coverage, though I am unable to make it work [link to recommended action](https://docs.codeclimate.com/docs/github-actions-test-coverage) Furthermore they have a bunch of integrations E.g. they have integrations for github issues (basically, we can generate issues off of whatever it finds. e.g. too many returns #130), 
Code climate also has support for exclusion of files like better code hub, but their configuration is easier to do via GUI, than through their .yaml file [advanced configuration documentation](https://docs.codeclimate.com/docs/advanced-configuration).
This is the result from the main branch
![image](https://user-images.githubusercontent.com/11597762/159122936-8a6aa68e-3dab-4aff-bd12-a9f0b8794884.png)
#### Highlights
The major issues code climate finds are:
- code duplication
- too many return statements 

### SoundCloud (sonarcloud)
Sonar cloud seems to be the largest and more categorized. It looks into different types of review e.g. security, bugs, duplication etc. and grades each one separately. Also keeping track over time.  It has its own github action that I have setup, but as above comment states, I am struggling with an error. The automated pull request checker seems to work though. These are our results from sonarcloud on the main branch:
![image](https://user-images.githubusercontent.com/11597762/159125932-9056a40d-290a-4ea7-b157-00d16be92fe3.png)
#### Highlights
The major issues are:
- passwords are hardcoded in the tests (security)
- there should be an **alt** attribute on<img> (bugs)
- TODOs, unused variables etc. (code smells)

**Comment by Lucki2g** [comment]
> Could also add this [project](https://github.com/gojp/goreportcard). I got it running locally: ![image](https://user-images.githubusercontent.com/11947367/158688728-aa620ec6-9d1b-4254-b1da-080ba1f3b741.png)

I feel like the other three are sufficient. 
I did look it through though, however it seems to me we need a go get path, which is not just our git hub repo, as it seems.
![image](https://user-images.githubusercontent.com/11597762/159127605-e5c311d6-f692-4c15-ba83-d97189772800.png)

**Comment by Lucki2g** [comment]
# Setup
### Better Code Hub
Login to their website and add the repository (only public)
Create .bettercodehub.yml in root directory
### Climate Code
Login to their website and add repository (only public)
Go to repo settings (on website) and add wanted integrations
For test coverage create an action secret (CC_TEST_REPORTER_ID) with the id from website [couldn't make it work] - old action can still be viewed in actions yml file
### SonarCloud
Login to their website and add repository
create sonar-project.properties in root directory
For github action add SONAR_TOKEN found on website to secrets (would not work caused by other CI)
