### ISSUE TITLE
Add detailed endpoint monitoring in Grafana

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#121]
From the end of issues #103 that we closed to start getting data from minitwit to grafana. 

Now would we like to add more detailed monitoring to the specific endpoints.

For the overall info we could add:

- [x] Error rate as % number
- [x] Error rate as graph (number over time/ avg?)

So for each endpoint we could add a row

- [x] Status code responses (bar chart)
- [x] Average response time graph
- [x] 90%  response time percentile 
- [x] 95%  response time percentile

inspiration: 
- https://grafana.com/grafana/dashboards/10445
- https://grafana.com/grafana/dashboards/12890

**Comment by Turboen** [comment]
#131 - See this pull request (I made some upsies commiting to wrong branch)
