### ISSUE TITLE
Fix "return_statements" issue in database/followerRepository.go

### ISSUE THREAD

**Issue by Lucki2g** [DevelOpsITU/MiniTwit#130]
Function `FollowUser` has 5 return statements (exceeds 4 allowed).

https://codeclimate.com/github/DevelOpsITU/MiniTwit/database/followerRepository.go#issue_6235d9016d4f5a000100005b

**Comment by Lucki2g** [comment]
This was for testing github issue integration for code climate

**Comment by DannyDelic** [comment]
For the issues pertaining code quality in terms of return statements, I have marked those with won't fix - when I checked the code in particular, refactoring did not make sense - if we were to refactor, that would mean we would have a generic handler for the functions that talk with the ORM, we do not, and I think it's merely a "nice-to-have" in the terms of the project scope.

**Comment by DannyDelic** [comment]
It might be interesting to at one point (if the opportunity presents itself), just to run through all the code quality issues, such as with codeclimate here: https://codeclimate.com/github/DevelOpsITU/MiniTwit/issues.
