### ISSUE TITLE
More metrics for Grafana

### ISSUE THREAD

**Issue by Zavir** [DevelOpsITU/MiniTwit#135]
Could be nice to have even more metrics for Grefana. Find inspiration from the flask application displayed in the session 8 lecture.

**Comment by Lucki2g** [comment]
Heatmap examples
![image](https://user-images.githubusercontent.com/11597762/160213977-61f346d9-1d24-438e-8eaf-58232b5a4fdd.png)

**Comment by Lucki2g** [comment]
Been searching and searching for a way to create continues profiling analysis for our current setup, but it seems to be nothing prometheus supports out the box, and hard for grafana to visualize. I found this alternative, but it is completely new service:

https://github.com/pyroscope-io/pyroscope

**Comment by Lucki2g** [comment]
What do you guys say? Is continues profiling important for us. Should we integrate another service?

**Comment by ValarMarkhulis** [comment]
Looks cool. But what about the profiler @Thomsen96 found called jaeger? Does it not do the same? I know it integrates well with Grafana

**Comment by Thomsen96** [comment]
Get this done :)
