### ISSUE TITLE
Serve "/register"

### ISSUE THREAD

**Issue by Lucki2g** [DevelOpsITU/MiniTwit#14]
✔️ Serve the GET request
✔️ Create user in database
⚠️ Error handling
✔️ Redirection to /login on success

TODO: 
- Better input confirmation. e.g. Regex for email. Valid characters etc.
~There is no SQL injection protection from the register form fields! This also goes for /login~

**Comment by Lucki2g** [comment]
It is not really error handling, more input validation. 
E.g. it is currently allowed to have an email just be a '@', which makes no sense.

**Comment by Thomsen96** [comment]
Add pull request

**Comment by Zavir** [comment]
@Lucki2g Can you close the issue if you think its done :-)
