### ISSUE TITLE
Add active monitoring

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#150]
In Grafana it is possible to setup alerts when i.e.
- Disk space is above a threshold
- Ram usage is high for more then 15 minutes
- Response times are slower than X
- Increase in errors
- ... 

Then send an email, send a message on discord or something else telegram? Signal?...

This falls in line with the [lecture 6](https://github.com/itu-devops/lecture_notes/blob/master/sessions/session_06/Session%206.ipynb) Where we learn about passive vs active monitoring. 

When we have active monitoring it will also help us to get closer to the goal of continuous delivery

**Comment by Lucki2g** [comment]
will continue to work on same branch as #135

**Comment by Lucki2g** [comment]
Minitwit
- [ ] Ram usage above 80%
- [ ] Response time for 95 Quantile of requests is >100ms
- [ ] Error rate is above 0.1

**Comment by Turboen** [comment]
![image](https://user-images.githubusercontent.com/61050781/160292396-b0343a51-b6bb-4c87-8698-e6b849c4a81f.png)

Added alerts for:
- [x] Disk space
- [x] Ram usage
- [x] Response time
- [x] Errors
