### ISSUE TITLE
Scrape database stats

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#151]
To get cool graphs of how many users there exists in the database do we need to add a scraper that can basicaly make the queries from https://grafana.thomsen-it.dk/d/nwWEUkP7k/minitwit-business-intelligence?orgId=1 and exports this data through prometheus. 

Solutions:
- Add to DataScraper
- Add to Minitwit
- Make a new scraper. 

**This is so we are able to add timelines**

**Comment by Lucki2g** [comment]
I went with the easiest of the solutions (adding more prometheus metrics to minitwit)

**Comment by Turboen** [comment]
Why do we need this? Why is it not enough with the current setup?
