### ISSUE TITLE
Automatic cleanup after tests have run

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#16]
In connection with task #12, then when the test have run against the web application are we currently missing a way to clean up the users. This causes the public timeline to be quite spammed. Se image below.

Suggestions to solve the issue

- Database script to remove test users and twits
- Flag the twits to not show them
- Add endpoint to delete a user and their twits, to call automatically when test case is done

![billede](https://user-images.githubusercontent.com/32035863/153774806-98d180bb-4314-429d-aba1-0e1a44859e15.png)

**Comment by Lucki2g** [comment]
Can this be closed since we use in:memory dbs now that automaticly clean up?

**Comment by Thomsen96** [comment]
Yes for the unit tests we use the in memory database so this is done.
