### ISSUE TITLE
Pen testing of group E

### ISSUE THREAD

**Issue by Lucki2g** [DevelOpsITU/MiniTwit#160]
Try to help your fellow colleagues by pen-testing their system. Remember that the goal is to help not to hinder. Send them a report of what you find.

For a given group, their "fellow colleagues" are represented by the next group in the [repositories](https://github.com/itu-devops/lecture_notes/blob/master/repositories.py) file. Group R wraps back to evaluate group A.

- [ ] Do pen test of Group E
- [ ] Create Issue in Group E with results

**Comment by Lucki2g** [comment]
Would be a good idea to do #154 first. And then use the methods on group E

**Comment by ValarMarkhulis** [comment]
Done with this [issue on group E's repo](https://github.com/ChadIImus/Devoops/issues/35)
