### ISSUE TITLE
Seperate code

### ISSUE THREAD

**Issue by Turboen** [DevelOpsITU/MiniTwit#24]
Seperate code into helper functions and different files for easier reading and maintenance

**Comment by Lucki2g** [comment]
* Querying database
* Service to handle all database calls
* Controller to handle API calls
* Main to handle other classes
* Struct classes

**Comment by Lucki2g** [comment]
This seems to be very simple. Just keep the same package name, and go does the rest. [https://go.dev/doc/code](url)
