### ISSUE TITLE
Add repository pattern for database access

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#35]
https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-design

**Comment by Lucki2g** [comment]
Closeable?

**Comment by Thomsen96** [comment]
Kinda closeable. But we have not implemented clean repositories but we don't need to and the application is in a pretty nice state on that level.
