### ISSUE TITLE
Change of Cookie logic

### ISSUE THREAD

**Issue by Lucki2g** [DevelOpsITU/MiniTwit#36]
The cookie should not always be reset

**Comment by ValarMarkhulis** [comment]
There is still a problem, which I think is cookie related. When you follow a user and then go to his profile then the button to follow him is still there. Furthermore, the message is not cleared.
![image](https://user-images.githubusercontent.com/11947367/156526734-8e10cad9-901d-4b9d-a984-d35065f9394d.png)

**Comment by Lucki2g** [comment]
Problem is caused by a missing model property. We never passed the value **followed** used in the template file.
