### ISSUE TITLE
Move business logic from controllers to a business layer

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#40]
The package could be named logic. 

We could call the package from the controller package, and from the logic package we could use the repository pattern suggested in #35 

This would allow us to make a super clear cut between Presentation, Business logic and infrastructure giving a more clean architecture

**Comment by Thomsen96** [comment]
The only function that is left is the add_message

**Comment by Lucki2g** [comment]
Finished?

**Comment by ValarMarkhulis** [comment]
I would say so. @Thomsen96 Can you close this, if you agree?
