### ISSUE TITLE
Follow without login

### ISSUE THREAD

**Issue by Turboen** [DevelOpsITU/MiniTwit#50]
When going to a user's page, it should not be possible to follow if you are not logged in.

**Comment by ValarMarkhulis** [comment]
Should at least return a 401 Unauthorized to the user.

**Comment by ValarMarkhulis** [comment]
I guess the same should be done, when someone tries to unfollow someone, when they are not logged in?
![image](https://user-images.githubusercontent.com/11947367/155882293-954563d0-4a02-417b-b692-92d98ab37966.png)

**Comment by Lucki2g** [comment]
pullrequest #80
