### ISSUE TITLE
Support simulation api

### ISSUE THREAD

**Issue by Turboen** [DevelOpsITU/MiniTwit#53]
**Latest - GET**
/latest
Returns last request value (stored as int)

**Register - POST**
/register
Posts a user
Error -> 400
Success -> 204

**Messages - GET**
/msgs
Returns all messages from all users

**Messages from user - GET/POST**
/msgs/<username>
Get: returns all messages by user
Post: inserts message by user and returns 204

**Follows user - GET/POST**
/fllws/<username>
POST && follow: 
<username> is the user that wants to follow someone else
request.json["follow"] contains username of the one you wants to follow
- no user -> 404
- else -> insert into follower and return 204

POST && unfollow
- no user -> 404
- else -> Delete from follower and return 204

Get: 
- gets all users the username follows
- {no} is an argument on the request to specify limit

**Comment by ValarMarkhulis** [comment]
@Turboen, what is missing on this task?
