### ISSUE TITLE
Cookie not working in production

### ISSUE THREAD

**Issue by Lucki2g** [DevelOpsITU/MiniTwit#54]

**Comment by Lucki2g** [comment]
Solved however small changes needed to the vagrant file at #52 needed.
These are "written in inline shell"
echo "
export SERVER_HOST=104.248.142.100
export SERVER_PORT=8080
" >> ~/.profile

**Comment by ValarMarkhulis** [comment]
Still a problem, since not all controllers use the new config described in #67. 
![image](https://user-images.githubusercontent.com/11947367/156162399-3856cc46-5c62-48ee-8da4-3ba4c265d2cb.png)

**Comment by Thomsen96** [comment]
Closed with #81
