### ISSUE TITLE
Format epoch time to correct timestamp format

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#57]
From the original Minitwit there were a function that converted to epoch time from the database to a specific string.

Make this function and use it the Go Application

**Comment by ValarMarkhulis** [comment]
Right now it looks like this (On current dev branch):
![image](https://user-images.githubusercontent.com/11947367/155091895-dde077a6-9f1b-4fac-8ab2-87f9879818da.png)

Should look like this:
![image](https://user-images.githubusercontent.com/11947367/155092345-f641df43-5909-4bcc-9410-cbb7f42100cc.png)

**Comment by ValarMarkhulis** [comment]
Fixed in #82 by @Zavir
