### ISSUE TITLE
Conterize application

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#61]
Dockerize the go application with the db.
Create a make file that does the following:
- Build the go file to an executable
- Run the application
- Run the application with hot reloading (Use cmd "fresh") 
- Run tests (Either python or go tests)
- Build a docker image
- Run container with docker image
- Push image to docker registry

**Comment by ValarMarkhulis** [comment]
Still need to do tests and push to docker registry.
