### ISSUE TITLE
Setup CI/CD

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#63]

**Comment by Zavir** [comment]
https://github.com/itu-devops/itu-minitwit-ci

**Comment by Lucki2g** [comment]
Useful for Go specific travis.yml: [travis go doc](https://docs.travis-ci.com/user/languages/go/)

**Comment by Lucki2g** [comment]
Currently struggling with travis not accepting the ecnrypted ssh key. I found out this is a known problem on windows: [problem](https://github.com/travis-ci/travis-ci/issues/4746)
I tried using git bash to go trough WSL which is said to work. Still nothing.
I am yet to try a VM...
