### ISSUE TITLE
Discussion about Travis and flows and actions

### ISSUE THREAD

**Issue by Thomsen96** [DevelOpsITU/MiniTwit#69]
When using Travis we can define what should happen at different steps could be:

- [x] Pull request to dev

  - Linting, build tests and system test

- [x] Commit to dev (merge request accepted) 

  - Linting, build docker image,  test docker image, publish with dev tag?

- [x] Commit to main (merge request accepted) 

  - Linting, build docker image,  test docker image, publish with latest tag?

**Comment by ValarMarkhulis** [comment]
Working on task:

- Pull request to dev
  - Linting, build tests and system test

**Comment by ValarMarkhulis** [comment]
We will run into trouble on the 22/3/22, when our Travis CI trial runs out:
![image](https://user-images.githubusercontent.com/11947367/157289413-6cbc878e-f11e-4358-92b4-43110cfcf54f.png)

I can try to ask on teams, if anyone in the other groups found a way to extend the trial or an alternative.

**Comment by ValarMarkhulis** [comment]
For the "Commit to main (merge request accepted)" step/task we should 
build docker image, test docker image, publish with a git commit hash tag to docker hub.
