### ISSUE TITLE
Jinja get_flashed_messages

### ISSUE THREAD

**Issue by ValarMarkhulis** [DevelOpsITU/MiniTwit#9]
In file layout.html in the jinja code the function "get_flashed_messages" is called. This fetches message from the cookie of the previous request. This is supported natively in flask with the function flash(), where a message can be stored. To decode the session cookies created by flask use this [python package](https://pypi.org/project/flask-cookie-decode/#usage). An example can be seen below, where we created a twit, and in the request session cookie the following request contained the cookie `eyJfZmxhc2hlcyI6W3siIHQiOlsibWVzc2FnZSIsIllvdXIgbWVzc2FnZSB3YXMgcmVjb3JkZWQiXX1dLCJ1c2VyX2lkIjoyMDR9.YgfcgA.TdDhr7sTxJvprq0zNFn1QoErJFQ`

which decoded with the command ` fcd decode eyJfZmxhc2hlcyI6W3siIHQiOlsibWVzc2FnZSIsIllvdXIgbWVzc2FnZSB3YXMgcmVjb3JkZWQiXX1dLCJ1c2VyX2lkIjoyMDR9.YgfcgA.TdDhr7sTxJvprq0zNFn1QoErJFQ` gave this json output:
```json
{
  "_flashes": [
    {
      " t": [
        "message",
        "Your message was recorded"
      ]
    }
  ],
  "user_id": 204
}
```

![image](https://user-images.githubusercontent.com/11947367/153719226-715303ae-bed6-420b-b9ff-53b0e8537102.png)

![image](https://user-images.githubusercontent.com/11947367/153719052-ec1c4354-0d39-441c-be46-edb903ca61f9.png)

@Thomsen96 and I were not able to find something similar to the flask flash() in Gonja or Gin.

**Comment by DannyDelic** [comment]
Solved according to: https://github.com/DevelOpsITU/MiniTwit/issues/6
